### ISSUE TITLE
Re-Organization of i18n files needed

### ISSUE THREAD

**Issue by cknebel** [refugeehackathon/helperchain#3]
Currently unter /config/locales the english localized files are located. These files do not follow any structure/system and need to be reorganzied in alignment with the page structure.

**Comment by itadventurer** [comment]
Feel free to think about how to organize them in the best way ;)
It does not matter too much 'cause we will use a I18n service like http://crowdin.com to handle the translations

**Comment by itadventurer** [comment]
I think it is now quite convinient ;)
